# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Number of worker nodes to provision
  NB_WORKERS = default_i('NB_WORKERS', 2)
  BIND_PROXY = default_b('BIND_PROXY', true)
  # Memory and CPU for the VMs (2GB, 2Core)
  MEMORY = default_i('MEMORY', 2048)
  CPU = default_i('CPU', 2)
end

# Convenience methods
def default_s(key, default)
  ENV[key] && ! ENV[key].empty? ? ENV[key] : default
end
def default_i(key, default)
  default_s(key, default).to_i
end

def default_b(key, default)
  default_s(key, default).to_s.downcase == 'true'
end

def setup_repo (node, vm)
  vm.provision "shell",
    path: "scripts/kubeadm-setup-#{node}.sh"
#    args: ["--no-login"]
end
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # We start from the Ubuntu 16.04 Xenial
  config.vm.box = "ubuntu/xenial64"
  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  config.vm.provider "virtualbox" do |vb|
    vb.memory = MEMORY
    vb.cpus = CPU
  end

  # Define VMs:
  # - Manager
  config.vm.define "master", primary: true do |master|
    master.vm.hostname = "master.vagrant.vm"
    master.vm.network "private_network", ip: "192.168.99.100"
    if BIND_PROXY
      # Bind kubernetes default proxy port
      master.vm.network "forwarded_port", guest: 8001, host: 8001
      master.vm.provision :shell, inline: <<-SHELL
        mkdir -p /etc/systemd/system/kubectl-proxy.service.d/
        touch /etc/systemd/system/kubectl-proxy.service.d/10-kubectl-proxy.conf
	sed -i 's/"KUBECTL_PROXY_ARGS=.*"/"KUBECTL_PROXY_ARGS=--port 8001 --accept-hosts='.*' --address=0.0.0.0"/' /etc/systemd/system/kubectl-proxy.service.d/10-kubectl-proxy.conf
	systemctl daemon-reload
        #curl -o kube-flannel.yml https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml
       # sed -i.bak 's|"/opt/bin/flanneld",|"/opt/bin/flanneld", "--iface=enp0s8",|' kube-flannel.yml
       # kubectl apply -f kube-flannel.yml
	#service restart kubectl
	#sudo systemctl daemon-reload
        #sudo systemctl restart kubelet
      SHELL
    end
    # Save options needed for master setup
 #   master.vm.provision :shell, inline: <<-SHELL
 #     > /root/.kubeadm-options
 #   SHELL
    # kubeadm will use the first network interface, which is the NAT interface
    # on VirtualBox and is not routable -- See OraBug 26540925
#    master.vm.provision :shell, inline: <<-SHELL
#      echo -n " --apiserver-advertise-address 192.168.99.100" >> /root/.kubeadm-options
#      sed -i 's/\\(- --kube-subnet-mgr\\)/\\1\\n        - --iface=eth1/' /usr/local/share/kubeadm/flannel.yaml
#    SHELL
    setup_repo("master", master.vm)
  end
  # - Workers
  (1..NB_WORKERS).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.hostname = "worker#{i}.vagrant.vm"
      ip = 100 + i
      worker.vm.network "private_network", ip: "192.168.99.#{ip}"
      if Vagrant.has_plugin?("vagrant-hosts")
        worker.vm.provision :hosts, :sync_hosts => true
      end
      setup_repo("worker", worker.vm)
    end
  end
  config.vm.provision "shell",
    path: "scripts/inst_proc.sh"
end
